apiVersion: apps/v1
kind: Deployment
metadata:
  name: depapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app:  webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: dep
        app:  webapp
    spec:
      containers:
        - name: frontend
          image: anupdudhe/frontendrds
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
                  requests:
                        memory: "32Mi"
                        cpu: "75m"
                  limits:     
                        memory: "64Mi"
                        cpu: "140m"
---
apiVersion: autosacling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: depapp
  minReplicas:  1
  maxReplicas:  4
  metrics:  
    - type: Resource
      resources:
        name:  cpu
        target: 
          type: Utilization
          averageUtilization: 50
