apiVersion: apps/v1
kind: Deployment
metadat:
  name: depapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector: 
    matchLabels:
      app:  webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: dep
        app:  webapp
    spec:
      containers:
        - name: frontend
          image: anupdudhe/frontendrds
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
                  requests:
                        memory: "32Mi"
                        cpu: "75m"
                  limits:     
                        memory: "64Mi"
                        cpu: "140m"
