apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonapp
  labels:
    app: daemonset
spec:
  selector:
    matchLabels:
      app: daemonset
  template:
    metadata:
      labels:
        name: daemonapp
        app: daemonset
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.3.6
        ports:
        - containerPort: 80
          protocol: TCP
