apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-v1
  labels:
    app: dep-app1
spec:
  strategy:
      type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1

  selector:
    matchLabels:
      app: dep-app1
  # selector:
  #   # matchExpressions:
  #   # - {key: app, operator: In, values: ['dep-app', 'dep-app1']}
  #   # - {key: app, operator: Exists,}

  #   # matchLables:
  #   #   app:  dep-app1
  replicas: 6
  template:
    metadata:
      labels:
        name: httpdapp
        app: dep-app1
    spec:
      containers:
      - name: httpdapp
        image: httpd:latest
        ports:
        - containerPort: 80
          protocol: TCP



