apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: dep-app
spec:
  strategy:
      type: Recreate
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1

  selector:
    matchExpressions:
    - {key: app, operator: In, values: ['dep-app', 'depapp']}
    - {key: app, operator: Exists,}

    # matchLables:
    #   app:  dep-app
  replicas: 6
  template:
    metadata:
      labels:
        name: nginxapp
        app: dep-app
    spec:
      containers:
      - name: nginxapp
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP



