apiVersion: v1
kind: Pod
metadata:
  name: podapp
  namespace: dev
  labels:
    app: prac-app
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
      name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: podservice
  namespace: dev
spec:
  type: NodePort
  selector:
    app: prac-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
